language: julia

os:
    - linux

julia:
    - 1.3

addons:
  apt:
    packages:
      - python3-matplotlib
env:
  matrix:
    - PYTHON=python3 # python 3.5

before_install:
    - sudo apt-get update

notifications:
    email: true

script:
  - julia --project --check-bounds=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'

 # after_success:
 #     - julia --project -e 'import Pkg; Pkg.add("Documenter")'
 #     - julia --project ./docs/make.jl

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
