language: julia

os:
    - linux

julia:
    - 1.3

notifications:
    email: true

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("Controlz")'

after_success:
    - julia --project -e 'import Pkg; Pkg.add("Documenter")'
    - julia --project ./docs/make.jl

