language: julia

os:
    - linux

julia:
    - 1.3

addons:
  apt:
    packages:
      - python3-matplotlib
env:
  matrix:
    - PYTHON=python3 # python 3.5

before_install:
    - sudo apt-get update

notifications:
    email: true

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("Controlz")'

 # after_success:
 #     - julia --project -e 'import Pkg; Pkg.add("Documenter")'
 #     - julia --project ./docs/make.jl

# https://discourse.julialang.org/t/mkdocs-material-in-documenter/13764/8
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      install:
        # mkdocs-material isn't available at the default py2 on travis-ci for now
        - sudo apt-get update
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda info -a
      script:
        - julia --project=docs -e 'import Pkg; Pkg.add("Documenter")'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
