language: julia

os:
    - linux

julia:
    - 1.3

addons:
  apt:
    packages:
      - python3-matplotlib
env:
  matrix:
    - PYTHON=python3 # python 3.5

before_install:
    - sudo apt-get update

notifications:
    email: true

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("Controlz")'

after_success:
    - julia --project -e 'import Pkg; Pkg.add("Documenter")'
    - julia --project ./docs/make.jl

