site_name:        ""
repo_url:         https://github.com/SimonEnsemble/Controlz.jl
site_description: Documentation for Controlz.jl
site_author:      SimonEnsemble

theme: cinder

extra_css:
  - assets/flux.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
  - mathjax-config.js

markdown_extensions:
  - pymdownx.arithmatex
  - extra
  - tables
  - fenced_code
  - toc:
      permalink: '#'
  #- toc:
  #    baselevel: 1
  #- mdx_math
extra:
  logo: assets/logo.png


docs_dir: 'build'

pages:
  - Controlz: index.md
  - Transfer Functions: tfs.md
