name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: 'Controlz'
  cancel-in-progress: true

jobs:
  unit-and-doc-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: checkout commit
        uses: actions/checkout@main

      - name: set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: '1.7.1'
      
      - name: build package
        uses: julia-actions/julia-buildpkg@latest
      
      - name: run tests
        run: julia --project --color=yes -e 'import Pkg; Pkg.test()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      
      - name: build and deploy docs
        run: julia --project --color=yes ./docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
